### ISSUE TITLE
Disambiguate replicated OS-specific .java files

### ISSUE THREAD

**Issue by dgrove-oss** [qbicc/qbicc-class-library#261]
OpenJDK has a source structuring pattern in java.base where there are multiple OS-specific copies of a Java class located in different sub-directories of the source tree (unix/classes, windows/classes, etc).  Normally, the OpenJDK build process is building for a particular target platform, so only one version is selected and included in the produced jar file.   Qbicc's build process is different, we copy _all_ of OS-specific files into a single combined source tree with a "last write wins" strategy and then rely on patching/replacing conflicts by copying our own sources last.  This is a workable strategy, but to be correct it requires that we have our own version of every duplicated OS-specific Java file to ensure that we actually resolve the conflicts and don't just end up with the last version copied (which is almost always the windows version).  

There are 33 such classes in OpenJDK 17.0.3 java.base's src tree that need this treatment, listed below:

- [x] java/io/DefaultFileSystem.java
- [x] java/lang/ProcessEnvironment.java
- [x] java/lang/ProcessImpl.java
- [x] java/lang/Terminator.java
- [ ] java/net/DefaultDatagramSocketImplFactory.java
- [ ] java/net/DefaultInterface.java
- [ ] java/net/PlainSocketImpl.java
- [ ] jdk/internal/loader/ClassLoaderHelper.java
- [x] jdk/internal/loader/FileURLMapper.java
- [x] jdk/internal/misc/OSEnvironment.java
- [ ] jdk/internal/platform/SystemMetrics.java
- [x] sun/net/NetHooks.java
- [ ] sun/net/PortConfig.java
- [ ] sun/net/dns/ResolverConfigurationImpl.java
- [ ] sun/net/www/protocol/file/Handler.java
- [x] #262
- [ ] sun/net/www/protocol/jar/JarFileFactory.java
- [ ] sun/nio/ch/DatagramDispatcher.java
- [x] sun/nio/ch/DefaultAsynchronousChannelProvider.java
- [x] sun/nio/ch/DefaultSelectorProvider.java
- [x] sun/nio/ch/FileDispatcherImpl.java
- [x] sun/nio/ch/FileKey.java
- [ ] sun/nio/ch/NativeThread.java
- [ ] sun/nio/ch/PipeImpl.java
- [ ] sun/nio/ch/SinkChannelImpl.java
- [ ] sun/nio/ch/SocketDispatcher.java
- [ ] sun/nio/ch/SourceChannelImpl.java
- [ ] sun/nio/ch/UnixDomainSocketsUtil.java
- [x] sun/nio/fs/DefaultFileSystemProvider.java
- [ ] sun/nio/fs/DefaultFileTypeDetector.java
- [ ] sun/security/provider/NativePRNG.java
- [ ] sun/security/provider/NativeSeedGenerator.java
- [ ] sun/util/locale/provider/HostLocaleProviderAdapterImpl.java

**Comment by dmlloyd** [comment]
May overlap with #5.

**Comment by dgrove-oss** [comment]
Yep.  Definitely does.  I'll take a look to make sure the list & completion status is consistent and then close this one in favor of 5.

**Comment by dgrove-oss** [comment]
Updated #5 with current status.  Closing as a duplicate.
